set "objDir=./obj"
set "binDir=./bin"
set "wxWidgetsDir=C:\wxWidgets\lib\gcc810_x64_dll"
if exist "%objDir%" (
    rmdir /s /q "%objDir%"
)
if exist "%binDir%" (
    rmdir /s /q "%binDir%"
)
mkdir "%objDir%"
mkdir "%binDir%"
mkdir "%objDir%\Debug"
mkdir "%objDir%\Release"
mkdir "%binDir%\Debug"
mkdir "%binDir%\Release"
xcopy /s /e /i "%wxWidgetsDir%" "%binDir%\Debug\"
xcopy /s /e /i "%wxWidgetsDir%" "%binDir%\Release\"

g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxGraphData.cpp -o obj\Debug\wxGraphData.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxGridView.cpp -o obj\Debug\wxGridView.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxPaintView.cpp -o obj\Debug\wxPaintView.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxWidgetsLab2App.cpp -o obj\Debug\wxWidgetsLab2App.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxWidgetsLab2Main.cpp -o obj\Debug\wxWidgetsLab2Main.o
g++.exe -LC:\wxWidgets\lib\gcc810_x64_dll -LC:\wxWidgets\include -LC:\wxWidgets\lib\gcc810_x64_dll -LC:\wxWidgets\include -o bin\Debug\wxWidgetsLab2.exe obj\Debug\wxGraphData.o obj\Debug\wxGridView.o obj\Debug\wxPaintView.o obj\Debug\wxWidgetsLab2App.o obj\Debug\wxWidgetsLab2Main.o   C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_net.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_xml.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_adv.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_aui.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_core.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_gl.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_html.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_media.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_propgrid.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_ribbon.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_richtext.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_stc.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_webview.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_xrc.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_net.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_xml.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_adv.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_aui.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_core.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_gl.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_html.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_media.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_propgrid.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_ribbon.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_richtext.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_stc.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_webview.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_xrc.a -mwindows

g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxGraphData.cpp -o obj\Release\wxGraphData.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxGridView.cpp -o obj\Release\wxGridView.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxPaintView.cpp -o obj\Release\wxPaintView.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxWidgetsLab2App.cpp -o obj\Release\wxWidgetsLab2App.o
g++.exe -Wall -g -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -I..\wxWidgetsLab2 -IC:\wxWidgets\include -IC:\wxWidgets\lib\gcc810_x64_dll\mswu -c C:\Users\stud\Desktop\labs\wxWidgetsLab2\wxWidgetsLab2Main.cpp -o obj\Release\wxWidgetsLab2Main.o
g++.exe -LC:\wxWidgets\lib\gcc810_x64_dll -LC:\wxWidgets\include -LC:\wxWidgets\lib\gcc810_x64_dll -LC:\wxWidgets\include -o bin\Release\wxWidgetsLab2.exe obj\Release\wxGraphData.o obj\Release\wxGridView.o obj\Release\wxPaintView.o obj\Release\wxWidgetsLab2App.o obj\Release\wxWidgetsLab2Main.o   C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_net.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_xml.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_adv.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_aui.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_core.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_gl.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_html.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_media.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_propgrid.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_ribbon.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_richtext.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_stc.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_webview.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_xrc.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_net.a C:\wxWidgets\lib\gcc810_x64_dll\libwxbase32u_xml.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_adv.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_aui.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_core.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_gl.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_html.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_media.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_propgrid.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_ribbon.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_richtext.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_stc.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_webview.a C:\wxWidgets\lib\gcc810_x64_dll\libwxmsw32u_xrc.a -mwindows
