#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -I../wxWidgetsLab2
CFLAGS_DEBUG = $(CFLAGS) -g `wx-config  --static=no --unicode=yes --debug=yes --cflags`
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  `wx-config  --static=no --unicode=yes --debug=yes --libs` $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/wxWidgetsLab2

INC_RELEASE = $(INC) -I../wxWidgetsLab2
CFLAGS_RELEASE = $(CFLAGS) -O2 `wx-config  --static=no --unicode=yes --debug=no --cflags`
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  -s `wx-config --static=no --unicode=yes --debug=no --libs` $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/wxWidgetsLab2

OBJ_DEBUG = $(OBJDIR_DEBUG)/wxGraphData.o $(OBJDIR_DEBUG)/wxGridView.o $(OBJDIR_DEBUG)/wxPaintView.o $(OBJDIR_DEBUG)/wxWidgetsLab2App.o $(OBJDIR_DEBUG)/wxWidgetsLab2Main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/wxGraphData.o $(OBJDIR_RELEASE)/wxGridView.o $(OBJDIR_RELEASE)/wxPaintView.o $(OBJDIR_RELEASE)/wxWidgetsLab2App.o $(OBJDIR_RELEASE)/wxWidgetsLab2Main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/wxGraphData.o: wxGraphData.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c wxGraphData.cpp -o $(OBJDIR_DEBUG)/wxGraphData.o

$(OBJDIR_DEBUG)/wxGridView.o: wxGridView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c wxGridView.cpp -o $(OBJDIR_DEBUG)/wxGridView.o

$(OBJDIR_DEBUG)/wxPaintView.o: wxPaintView.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c wxPaintView.cpp -o $(OBJDIR_DEBUG)/wxPaintView.o

$(OBJDIR_DEBUG)/wxWidgetsLab2App.o: wxWidgetsLab2App.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c wxWidgetsLab2App.cpp -o $(OBJDIR_DEBUG)/wxWidgetsLab2App.o

$(OBJDIR_DEBUG)/wxWidgetsLab2Main.o: wxWidgetsLab2Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c wxWidgetsLab2Main.cpp -o $(OBJDIR_DEBUG)/wxWidgetsLab2Main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/wxGraphData.o: wxGraphData.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c wxGraphData.cpp -o $(OBJDIR_RELEASE)/wxGraphData.o

$(OBJDIR_RELEASE)/wxGridView.o: wxGridView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c wxGridView.cpp -o $(OBJDIR_RELEASE)/wxGridView.o

$(OBJDIR_RELEASE)/wxPaintView.o: wxPaintView.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c wxPaintView.cpp -o $(OBJDIR_RELEASE)/wxPaintView.o

$(OBJDIR_RELEASE)/wxWidgetsLab2App.o: wxWidgetsLab2App.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c wxWidgetsLab2App.cpp -o $(OBJDIR_RELEASE)/wxWidgetsLab2App.o

$(OBJDIR_RELEASE)/wxWidgetsLab2Main.o: wxWidgetsLab2Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c wxWidgetsLab2Main.cpp -o $(OBJDIR_RELEASE)/wxWidgetsLab2Main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

